### ISSUE TITLE
metadata.json doesn't set dependencies

### ISSUE THREAD

**Issue by bhourigan** [nubisproject/nubis-puppet-eip#10]
According to puppet documentation[1] the "dependencies" parameter is required. Although there is no errors from librarian-puppet, there is an error from puppet. A rather strange error. I can confirm once "dependencies" is added it's fixed.

```
    amazon-ebs-amazon-linux: Error: Puppet::Parser::AST::Resource failed with error ArgumentError: Could not find declared class nubis_eip::eip at /tmp/packer-puppet-masterless/manifests/init.pp:5 on node ip-172-31-13-158.us-west-2.compute.internal
```

[1] https://docs.puppetlabs.com/puppet/latest/reference/modules_publishing.html#write-a-metadatajson-file

**Comment by limed** [comment]
Fixed with PR #13
